### ISSUE TITLE
A question about the pre-trained word embeddings

### ISSUE THREAD

**Issue by speedcell4** [yahshibu/nested-ner-tacl2020-flair#1]
Hello.

In section 3.2 of your paper, you said GloVe is used for initializing but at this part, you used `GoogleNews-vectors-negative300.bin`. Could you please explain what is this?

https://github.com/yahshibu/nested-ner-tacl2020-flair/blob/47706c88c87043faf9253e275f373bc637a908c1/reader/reader.py#L9

**Comment by yahshibu** [comment]
Thank you for letting me know the explanation in the paper is not enough by itself. I failed to mention this in detail. I'm sorry.

We used GloVe embedding only for the first model (without any contextualized embeddings). We used the above publicly-available embeddings for the third model with Flair framework. The reason for that is [Strakova et al. (2019)](https://www.aclweb.org/anthology/P19-1527/) also used word2vec embeddings.

**Comment by speedcell4** [comment]
Thank you so much for your quick response. 
So the reason for using `GoogleNews-vectors` is just to follow previous work settings? Not because of the experimental performance?
And one more question, I can not find BERT in your code. How to integrate them?

**Comment by speedcell4** [comment]
Sorry, I found the BERT part in your [other repository](https://github.com/yahshibu/nested-ner-tacl2020-transformers). Please ignore the second question.

**Comment by yahshibu** [comment]
> Not because of the experimental performance?

Yes, it is to follow previous work. We didn't try GloVe for this model, so we cannot say which is better, or we cannot say what is the best combination...


> And one more question, I can not find BERT in your code. How to integrate them?

We are using [Flair framework](https://github.com/flairNLP/flair). It supports BERT. BERT is called here.
https://github.com/yahshibu/nested-ner-tacl2020-flair/blob/a45468d0d0d4e12ba0544a7205a2a46c7beb7721/model/sequence_labeling.py#L34

**Comment by speedcell4** [comment]
Thank you so much for your help~

**Comment by yahshibu** [comment]
You're welcome. And, thank you for your nice questions.

**Comment by speedcell4** [comment]
Sorry, another question about this.
In your paper, You have mentioned
> We use the uncased version of BERT large model as a contextual word embeddings generator without fine-tuning

Then I guess at here `fine_tune  = False`, then `layers = "-1,-2,-3,-4,-5,-6,-7,-8"`, and this will result in an 8192-dimensional vector for each token. Is this correct?

https://github.com/yahshibu/nested-ner-tacl2020-flair/blob/a45468d0d0d4e12ba0544a7205a2a46c7beb7721/model/sequence_labeling.py#L35

**Comment by yahshibu** [comment]
Yes, that's correct. Fig.7 in [the original paper of BERT](https://www.aclweb.org/anthology/N19-1423/) shows that the concatenation of the representations of the last four layers is good in applying BERT (base) to the CoNLL-2003 NER task. I used the last eight layers just because BERT (large) has twice more layers than BERT (base). I didn't explore another way of concatenation or another way of combination (weighted sum, etc.) on ACE2004, ACE2005, or GENIA.

**Comment by speedcell4** [comment]
Thank you for your help~
