### ISSUE TITLE
Second best with Flair+BERT 

### ISSUE THREAD

**Issue by matirojasg** [yahshibu/nested-ner-tacl2020-flair#3]
Hi, I am running your model using both BERT and Flair, but it turns out that I get good results when training (i.e., on the validation set), but then when loading the best model to test on the testing partition, the results drop to almost 0 f1-score, what could be the problem? With the other embedding combinations, this does not happen.

Could you check if everything is working ok?

Regards

**Comment by yahshibu** [comment]
Hi, thank you for having an interest in our work!
I have no idea about the cause of what's happening in your experiment. I've never encountered such an issue. Could you tell me more detailed information (code and data used, etc.)?

**Comment by matirojasg** [comment]
I think that this problem had to do with the fact that I used the original Flair functions: FlairEmbeddings, TransformerWordEmbeddings and not the ones created by you, because now I tested it in genia and it works fine.

The problem is that I want to test in another dataset, and the code is not working. I want to try it in the GermEval dataset. Here is the data: https://drive.google.com/drive/folders/1DoeeOhgsHd89WMLBIVT9WwG3SUTSG181?usp=sharing. 

The first error that appears following your instructions is the following:

```
Traceback (most recent call last):
  File "train.py", line 200, in <module>.
    f1 = get_f1(ner_model, 'dev')
  File "train.py", line 51, in get_f1
    pred_sequence_entities = model.predict(token_batch, mask_batch_var)
  File "/content/gdrive/My Drive/nested-ner-tacl2020-flair/model/sequence_labeling.py", line 231, in predict
    preds_each.append(predict_recursively(preds_batch[i, :], energy_batch[i, :, :, :, :], 0))
  File "/content/gdrive/My Drive/nested-ner-tacl2020-flair/model/sequence_labeling.py", line 222, in predict_recursively
    nested_preds = decode_nest(energy[start_tmp:end_tmp, :, :, :])
  File "/content/gdrive/My Drive/nested-ner-tacl2020-flair/module/crf.py", line 301, in decode_nest
    if (indices_3[t + 1] == back_pointer[t + 1]).nonzero().numel() == 0:
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

I fixed it with this line:

`indices_3 = indices_3.cuda()`

Then, when training with BERT+Flair, the following error appears:

`/usr/local/lib/python3.7/dist-packages/adabound/adabound.py:94: UserWarning: This overload of add_ is deprecated: add_(Number alpha, Tensor other) Consider using one of the following signatures instead: add_(Tensor other, *, Number alpha) (Triggered internally at /pytorch/torch/csrc/utils/python_arg_parser.cpp:1025.) exp_avg.mul_(beta1).add_(1 - beta1, grad) train: 20/750 loss: 41.4490, time left (estimated): 721.69sTraceback (most recent call last): File "train.py", line 163, in <module> loss = ner_model.forward(token_batch, label_batch, mask_batch_var) File "/content/gdrive/My Drive/nested-ner-tacl2020-flair/model/sequence_labeling.py", line 146, in forward output = self._get_rnn_output(tokens, mask=mask) File "/content/gdrive/My Drive/nested-ner-tacl2020-flair/model/sequence_labeling.py", line 104, in _get_rnn_output self.embeddings.embed(sentences) File "/usr/local/lib/python3.7/dist-packages/flair/embeddings/token.py", line 81, in embed embedding.embed(sentences) File "/usr/local/lib/python3.7/dist-packages/flair/embeddings/base.py", line 60, in embed self._add_embeddings_internal(sentences) File "/content/gdrive/My Drive/nested-ner-tacl2020-flair/module/embeddings.py", line 191, in _add_embeddings_internal mean = torch.mean(torch.cat(embeddings, dim=0), dim=0) NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat. This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function. Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode]. `

These are the embeddings used:

Word-embeddings: https://fasttext.cc/docs/en/crawl-vectors.html
Flair: 'de-forward', 'de-backward'
BERT: 'bert-base-german-cased'

**Comment by matirojasg** [comment]
I found the error. Some tokens of the German corpus are not found in the vocabulary of BERT nor the subtokens since they are characters. The solution was to assign a vector to these cases so that the program would not crash,

Thank you very much. Excellent work!

**Comment by yahshibu** [comment]
I see. It's good that you finally know the cause! Thanks.
